### PR TITLE
configure gdb plugins in the challenge initialization

### PR DESCRIPTION
**Pull request by mudongliang**

### CODE REVIEW

**Comment by ConnorNelson** [comment]
I don't think we want to force that specific `.gdbinit` as a default for users. 

I would be fine if we wanted to somehow better convey that `/opt/pwndbg` and `/opt/gef` exist and can be used with an `echo 'source /opt/pwndbg/gdbinit.py' > ~/.gdbinit` or `echo 'source /opt/gef/gef.py' > ~/.gdbinit`. I'm not totally sure what that better conveyance of information would look like; probably it could make sense as a challenge in the `debugging-refresher` module.

**Comment by mudongliang** [comment]
Yeah, this gdbinit looks really complicated for newbies.

**Comment by mudongliang** [comment]
I would like to enable pwndbg and find that .gdbinit includes "source /opt/pwndbg/gdbinit.py". So I post this PR

**Comment by mudongliang** [comment]
And there is another issue in gef. It has changed the installation method.

**Comment by ConnorNelson** [comment]
I just tested both of the above `echo` commands for using pwndbg/gef, and they both seem to work.

**Comment by mudongliang** [comment]
I have an idea. Maybe we can craft a challenge - pwndbg, gef to tell newbies that, we have installed many fancy plugins, you can enable anyone you like.

**Comment by mudongliang** [comment]
like many challenges in the welcome-dojo, this is an introduction for the functionability of dojo platform

**Comment by ConnorNelson** [comment]
This is a gdb capability. It should be discussed in the gdb module.

**Comment by mudongliang** [comment]
This is just an example. I checked dojos in pwncollege, Debugging-fresher is a good choice.

**Comment by mudongliang** [comment]
Let's close this PR

**Pull request closed without merging**
