### PR TITLE
Do not show Profile page for admin since it always returns 404

### PR DESCRIPTION
**Pull request by mudongliang**

### CODE REVIEW

**Comment by mudongliang** [comment]
?

**Comment by ConnorNelson** [comment]
I’m not sure that I understand what issue this PR addresses. Admins should be able to view their own profile (maybe not if they have their status set to hidden)?

**Comment by mudongliang** [comment]
I see. If admin is allowed to see its profile page, this PR is useless. Let's close it.

**Comment by mudongliang** [comment]
Even if you set admin as visible, the profile page still shows 404 :/

**Pull request closed without merging**
