### PR TITLE
Workspace: Handle service starts gracefully

### PR DESCRIPTION
**Pull request by ConnorNelson**

### CODE REVIEW

**Comment by ConnorNelson** [comment]
I think it would make sense to do something like use javascript to poll every second to see if the service is ready (e.g. container exists, container is running, service is running). Once that has been confirmed, let the iframe show up. In the meantime have a "loading" animation. Do this for 20s and then give up and tell the user no challenge is running.

**Comment by Scoder12** [comment]
does that mean that if you truly don't have a challenge running, you have to wait 20s to find out?

**Comment by ConnorNelson** [comment]
Yeah it definitely would.

What we could do is be more informative about the process as we are with SSH. Maybe instead we check if the container exists in any state at all (e.g. even just "Created"); if not, immediately report no challenge started, otherwise poll for service-readiness for ~20 seconds.

**Comment by ConnorNelson** [comment]
#478 has a better discussion of what this should look like.

**Pull request closed without merging**
