### PR TITLE
Update outdated README

### PR DESCRIPTION
**Pull request by Scoder12**
Should make setting up a development environment easier.

### CODE REVIEW

**Comment by ConnorNelson** [comment]
Super minor, but I prefer to put each sentence on its own line. This makes it easier when reading diffs to immediately see what sentences have been changed.

Also, as you said in your container-setup.sh PR, we should update the language now to reflect that `challenge-minimal` is now the default.

**Comment by Scoder12** [comment]
Zero idea why the diff looks like that.

**Comment by Scoder12** [comment]
Fixed it (hackily) with a force push. I don't think I rebased properly or something.

**Comment by ConnorNelson** [comment]
You had diff data in there (e.g. `<<<<<<< HEAD`). I went ahead and cleared that out, otherwise looks good to me!

**Pull request merged**
